### ISSUE TITLE
时区有问题

### ISSUE THREAD

**Issue by yelincx** [sy-records/MemorialDay#1]
wordpress下设置之后，是按照UTC 0的时间显示的，希望作者可以进一步修改。
不过不建议用benny版插件的方式直接设定时区为asia/shanghai的方式，那样虽然灰白会在对的时间显示，但是会让文章编辑器的后台和实际时区有差（比如设定shanghai就是差8小时）。

**Comment by SadPencil** [comment]
js下用以下代码就可以让【浏览器】取本地时区下的日期，作者可参考
`const date = new Date();
const day = date.getDate();
const month = date.getMonth()+1;
const year = date.getFullYear();
if (比较一下日期){
do some thing
}
`

**Comment by sy-records** [comment]
> wordpress下设置之后，是按照UTC 0的时间显示的，希望作者可以进一步修改。
> 不过不建议用benny版插件的方式直接设定时区为asia/shanghai的方式，那样虽然灰白会在对的时间显示，但是会让文章编辑器的后台和实际时区有差（比如设定shanghai就是差8小时）。

加在运行时就好了

**Comment by SadPencil** [comment]
让浏览器取本地时区不是更好吗，不一定假设用户都在一个时区吧

**Comment by sy-records** [comment]
> 让浏览器取本地时区不是更好吗，不一定假设用户都在一个时区吧

没意义，这肯定中国用的多... 默认就行了

**Comment by yelincx** [comment]
昨晚在测试站试了一下，是0区的时间。和国内差着8小时。
我用的是benny版插件，时区改成了Tokyo，不过就会有文章后台编辑器里时区差9个小时的现象，所以，偶尔用，偶尔改css代码……

**Comment by sy-records** [comment]
时区问题我已经更新了，在wordpress后台安装插件搜索：MemorialDay，安装由沈唁提供的那个插件就可以了

**Comment by yelincx** [comment]
看到了~
粗看了一下，目前的实现方法好像是和wp后台设定的时区一致是吧。

**Comment by sy-records** [comment]
嗯



---原始邮件---
发件人: "yelincx"<notifications@github.com&gt;
发送时间: 2020年4月6日(周一) 晚上8:16
收件人: "sy-records/MemorialDay"<MemorialDay@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;;
主题: Re: [sy-records/MemorialDay] 时区有问题 (#1)




 
看到了~
 粗看了一下，目前的实现方法好像是和wp后台设定的时区一致是吧。

**Comment by yelincx** [comment]
辛苦~果断卸载之前安装的其他同类插件
