### ISSUE TITLE
IE11浏览器无效

### ISSUE THREAD

**Issue by whsir** [sy-records/MemorialDay#2]
![image](https://user-images.githubusercontent.com/46343402/78414064-ec2a2b00-764c-11ea-8522-4715d5a28020.png)

**Comment by sy-records** [comment]
不用ie...

**Comment by sy-records** [comment]
😂没有ie调试，有空可以提个pr

**Comment by whsir** [comment]
垃圾IE (￣▽￣)"

**Comment by dyt5AAUI** [comment]
IE，这年头还有人用？

**Comment by yelincx** [comment]
IE连设置css代码都不生效……
话说“加在运行时”是什么意思？是指加载运行时吗还是就是加在运行时？

**Comment by sy-records** [comment]
> IE连设置css代码都不生效……
> 话说“加在运行时”是什么意思？是指加载运行时吗还是就是加在运行时？

你在说什么加载运行时？时区？
