### ISSUE TITLE
chrome, wp5.4, CST time, installed from WP admin page, doesn't work

### ISSUE THREAD

**Issue by ma-ji** [sy-records/MemorialDay#3]
Thanks for making this plugin.

**Comment by sy-records** [comment]
Thanks for using. Can you answer me a few questions? This plugin is mainly for Chinese people. 

1. Where are you using it? 
2. What time format do you use? 
3. Where is the time zone?

Maybe I can provide a time zone selection box or follow the WordPress time zone.

**Comment by sy-records** [comment]
Are you using it in the US? Should be `UT-6:00`

**Comment by ma-ji** [comment]
@sy-records 或许可以让插件用WP网站的时区设置呢？

**Comment by sy-records** [comment]
I have fixed it, can you try it? @ma-ji

**Comment by sy-records** [comment]
Update version 1.0.1 in the admin page of WordPress.

**Comment by ma-ji** [comment]
Looks good! 推荐加一个Ribbon功能，参考https://wordpress.org/plugins/black-ribbon/
谢谢！
